const COUNTRY_CODES: Record<string, string> = {
  // A
  'afghanistan': 'af', 'afganistán': 'af',
  'albania': 'al',
  'algeria': 'dz', 'argelia': 'dz',
  'andorra': 'ad',
  'angola': 'ao',
  'antigua and barbuda': 'ag', 'antigua y barbuda': 'ag',
  'argentina': 'ar',
  'armenia': 'am',
  'australia': 'au',
  'austria': 'at',
  'azerbaijan': 'az', 'azerbaiyán': 'az',
  // B
  'bahamas': 'bs',
  'bahrain': 'bh', 'baréin': 'bh',
  'bangladesh': 'bd',
  'barbados': 'bb',
  'belarus': 'by', 'bielorrusia': 'by',
  'belgium': 'be', 'bélgica': 'be', 'belgica': 'be',
  'belize': 'bz', 'belice': 'bz',
  'benin': 'bj', 'benín': 'bj',
  'bhutan': 'bt', 'bután': 'bt',
  'bolivia': 'bo',
  'bosnia & herzegovina': 'ba', 'bosnia and herzegovina': 'ba', 'bosnia y herzegovina': 'ba',
  'botswana': 'bw',
  'brazil': 'br', 'brasil': 'br',
  'brunei': 'bn',
  'bulgaria': 'bg',
  'burkina faso': 'bf',
  'burundi': 'bi',
  // C
  'cabo verde': 'cv', 'cape verde': 'cv',
  'cambodia': 'kh', 'camboya': 'kh',
  'cameroon': 'cm', 'camerún': 'cm', 'camerun': 'cm',
  'canada': 'ca', 'canadá': 'ca',
  'central african republic': 'cf', 'república centroafricana': 'cf',
  'chad': 'td',
  'chile': 'cl',
  'china': 'cn',
  'colombia': 'co',
  'comoros': 'km', 'comoras': 'km',
  'congo': 'cg',
  'costa rica': 'cr',
  "côte d'ivoire": 'ci', 'ivory coast': 'ci', 'costa de marfil': 'ci',
  'croatia': 'hr', 'croacia': 'hr',
  'cuba': 'cu',
  'curaçao': 'cw', 'curacao': 'cw',
  'cyprus': 'cy', 'chipre': 'cy',
  'czechia': 'cz', 'czech republic': 'cz', 'república checa': 'cz', 'republica checa': 'cz',
  // D
  'denmark': 'dk', 'dinamarca': 'dk',
  'djibouti': 'dj', 'yibuti': 'dj',
  'dominica': 'dm',
  'dominican republic': 'do', 'república dominicana': 'do',
  'dr congo': 'cd', 'democratic republic of the congo': 'cd', 'república democrática del congo': 'cd', 'republica democratica del congo': 'cd',
  // E
  'east timor': 'tl', 'timor-leste': 'tl',
  'ecuador': 'ec',
  'egypt': 'eg', 'egipto': 'eg',
  'el salvador': 'sv',
  'equatorial guinea': 'gq', 'guinea ecuatorial': 'gq',
  'eritrea': 'er',
  'estonia': 'ee',
  'eswatini': 'sz', 'swaziland': 'sz',
  'ethiopia': 'et', 'etiopía': 'et',
  // F
  'fiji': 'fj',
  'finland': 'fi', 'finlandia': 'fi',
  'france': 'fr', 'francia': 'fr',
  // G
  'gabon': 'ga', 'gabón': 'ga',
  'gambia': 'gm',
  'georgia': 'ge',
  'germany': 'de', 'alemania': 'de',
  'ghana': 'gh',
  'greece': 'gr', 'grecia': 'gr',
  'grenada': 'gd', 'granada': 'gd',
  'guatemala': 'gt',
  'guinea': 'gn',
  'guinea-bissau': 'gw',
  'guyana': 'gy',
  // H
  'haiti': 'ht', 'haití': 'ht',
  'honduras': 'hn',
  'hungary': 'hu', 'hungría': 'hu',
  // I
  'iceland': 'is', 'islandia': 'is',
  'india': 'in',
  'indonesia': 'id',
  'iran': 'ir', 'irán': 'ir',
  'iraq': 'iq', 'irak': 'iq',
  'ireland': 'ie', 'irlanda': 'ie',
  'israel': 'il',
  'italy': 'it', 'italia': 'it',
  // J
  'jamaica': 'jm',
  'japan': 'jp', 'japón': 'jp',
  'jordan': 'jo', 'jordania': 'jo',
  // K
  'kazakhstan': 'kz', 'kazajistán': 'kz',
  'kenya': 'ke', 'kenia': 'ke',
  'kiribati': 'ki',
  'north korea': 'kp', 'corea del norte': 'kp',
  'south korea': 'kr', 'corea del sur': 'kr', 'korea republic': 'kr', 'korea, republic of': 'kr',
  'kosovo': 'xk',
  'kuwait': 'kw',
  'kyrgyzstan': 'kg', 'kirguistán': 'kg',
  // L
  'laos': 'la',
  'latvia': 'lv', 'letonia': 'lv',
  'lebanon': 'lb', 'líbano': 'lb',
  'lesotho': 'ls',
  'liberia': 'lr',
  'libya': 'ly', 'libia': 'ly',
  'liechtenstein': 'li',
  'lithuania': 'lt', 'lituania': 'lt',
  'luxembourg': 'lu', 'luxemburgo': 'lu',
  // M
  'madagascar': 'mg',
  'malawi': 'mw',
  'malaysia': 'my', 'malasia': 'my',
  'maldives': 'mv', 'maldivas': 'mv',
  'mali': 'ml', 'malí': 'ml',
  'malta': 'mt',
  'marshall islands': 'mh', 'islas marshall': 'mh',
  'mauritania': 'mr',
  'mauritius': 'mu', 'mauricio': 'mu',
  'mexico': 'mx', 'méxico': 'mx',
  'micronesia': 'fm',
  'moldova': 'md', 'moldavia': 'md',
  'monaco': 'mc', 'mónaco': 'mc',
  'mongolia': 'mn',
  'montenegro': 'me',
  'morocco': 'ma', 'marruecos': 'ma',
  'mozambique': 'mz',
  'myanmar': 'mm',
  // N
  'namibia': 'na',
  'nauru': 'nr',
  'nepal': 'np',
  'netherlands': 'nl', 'países bajos': 'nl', 'paises bajos': 'nl',
  'new zealand': 'nz', 'nueva zelanda': 'nz',
  'nicaragua': 'ni',
  'niger': 'ne', 'níger': 'ne',
  'nigeria': 'ng',
  'north macedonia': 'mk', 'macedonia del norte': 'mk',
  'norway': 'no', 'noruega': 'no',
  // O
  'oman': 'om', 'omán': 'om',
  // P
  'pakistan': 'pk', 'pakistán': 'pk',
  'palau': 'pw',
  'palestine': 'ps', 'palestina': 'ps',
  'panama': 'pa', 'panamá': 'pa',
  'papua new guinea': 'pg', 'papúa nueva guinea': 'pg',
  'paraguay': 'py',
  'peru': 'pe', 'perú': 'pe',
  'philippines': 'ph', 'filipinas': 'ph',
  'poland': 'pl', 'polonia': 'pl',
  'portugal': 'pt',
  // Q
  'qatar': 'qa',
  // R
  'romania': 'ro', 'rumania': 'ro',
  'russia': 'ru', 'rusia': 'ru',
  'rwanda': 'rw',
  // S
  'saint kitts and nevis': 'kn', 'san cristóbal y nieves': 'kn',
  'saint lucia': 'lc', 'santa lucía': 'lc',
  'saint vincent and the grenadines': 'vc', 'san vicente y las granadinas': 'vc',
  'samoa': 'ws',
  'san marino': 'sm',
  'sao tome and principe': 'st', 'santo tomé y príncipe': 'st',
  'saudi arabia': 'sa', 'arabia saudita': 'sa', 'arabia saudí': 'sa',
  'senegal': 'sn',
  'serbia': 'rs',
  'seychelles': 'sc',
  'sierra leone': 'sl', 'sierra leona': 'sl',
  'singapore': 'sg', 'singapur': 'sg',
  'slovakia': 'sk', 'eslovaquia': 'sk',
  'slovenia': 'si', 'eslovenia': 'si',
  'solomon islands': 'sb', 'islas salomón': 'sb',
  'somalia': 'so',
  'south africa': 'za', 'sudáfrica': 'za', 'sudafrica': 'za',
  'south sudan': 'ss', 'sudán del sur': 'ss',
  'spain': 'es', 'españa': 'es', 'espana': 'es',
  'sri lanka': 'lk',
  'sudan': 'sd', 'sudán': 'sd',
  'suriname': 'sr',
  'sweden': 'se', 'suecia': 'se',
  'switzerland': 'ch', 'suiza': 'ch',
  'syria': 'sy', 'siria': 'sy',
  // T
  'taiwan': 'tw', 'taiwán': 'tw',
  'tajikistan': 'tj', 'tayikistán': 'tj',
  'tanzania': 'tz',
  'thailand': 'th', 'tailandia': 'th',
  'togo': 'tg',
  'tonga': 'to',
  'trinidad and tobago': 'tt', 'trinidad y tobago': 'tt',
  'tunisia': 'tn', 'túnez': 'tn', 'tunez': 'tn',
  'turkey': 'tr', 'turquía': 'tr', 'turquia': 'tr', 'türkiye': 'tr',
  'turkmenistan': 'tm', 'turcomanistán': 'tm',
  'tuvalu': 'tv',
  // U
  'uganda': 'ug',
  'ukraine': 'ua', 'ucrania': 'ua',
  'united arab emirates': 'ae', 'emiratos árabes unidos': 'ae',
  'united kingdom': 'gb', 'reino unido': 'gb',
  'united states': 'us', 'estados unidos': 'us', 'usa': 'us',
  'uruguay': 'uy',
  'uzbekistan': 'uz', 'uzbekistán': 'uz',
  // V
  'vanuatu': 'vu',
  'venezuela': 've',
  'vietnam': 'vn',
  // Y
  'yemen': 'ye',
  // Z
  'zambia': 'zm',
  'zimbabwe': 'zw',
  
  // FIFA specifics / UK nations
  'england': 'gb-eng', 'inglaterra': 'gb-eng',
  'scotland': 'gb-sct', 'escocia': 'gb-sct',
  'wales': 'gb-wls', 'gales': 'gb-wls',
  'northern ireland': 'gb-nir', 'irlanda del norte': 'gb-nir',
};

const CLUB_LOGOS: Record<string, string> = {
  'real madrid': 'https://media.api-sports.io/football/teams/541.png',
  'barcelona': 'https://media.api-sports.io/football/teams/529.png',
  'atlético de madrid': 'https://media.api-sports.io/football/teams/530.png',
  'atletico de madrid': 'https://media.api-sports.io/football/teams/530.png',
  'bayern múnich': 'https://media.api-sports.io/football/teams/157.png',
  'bayern munich': 'https://media.api-sports.io/football/teams/157.png',
  'borussia dortmund': 'https://media.api-sports.io/football/teams/165.png',
  'paris saint-germain': 'https://media.api-sports.io/football/teams/85.png',
  'manchester city': 'https://media.api-sports.io/football/teams/50.png',
  'manchester united': 'https://media.api-sports.io/football/teams/33.png',
  'liverpool fc': 'https://media.api-sports.io/football/teams/40.png',
  'arsenal': 'https://media.api-sports.io/football/teams/42.png',
  'juventus': 'https://media.api-sports.io/football/teams/496.png',
  'inter de milán': 'https://media.api-sports.io/football/teams/505.png',
  'inter de milan': 'https://media.api-sports.io/football/teams/505.png',
  'ac milan': 'https://media.api-sports.io/football/teams/489.png',
  'chelsea': 'https://media.api-sports.io/football/teams/49.png',
  'tottenham hotspur': 'https://media.api-sports.io/football/teams/47.png',
  'bayer leverkusen': 'https://media.api-sports.io/football/teams/168.png',
  'sporting cp': 'https://media.api-sports.io/football/teams/228.png',
  'aston villa': 'https://media.api-sports.io/football/teams/66.png',
  'benfica': 'https://media.api-sports.io/football/teams/211.png',
  'psv eindhoven': 'https://media.api-sports.io/football/teams/197.png',
  'feyenoord': 'https://media.api-sports.io/football/teams/202.png',
  'mónaco': 'https://media.api-sports.io/football/teams/91.png',
  'monaco': 'https://media.api-sports.io/football/teams/91.png',
  'celtic': 'https://media.api-sports.io/football/teams/252.png',
  'lille': 'https://media.api-sports.io/football/teams/94.png',
  'sevilla fc': 'https://media.api-sports.io/football/teams/536.png',
  'valencia cf': 'https://media.api-sports.io/football/teams/532.png',
  'villarreal': 'https://media.api-sports.io/football/teams/533.png',
  'celta de vigo': 'https://media.api-sports.io/football/teams/538.png',
  'mallorca': 'https://media.api-sports.io/football/teams/797.png',
  'osasuna': 'https://media.api-sports.io/football/teams/727.png',
  'getafe': 'https://media.api-sports.io/football/teams/546.png',
  'rayo vallecano': 'https://media.api-sports.io/football/teams/728.png',
  'las palmas': 'https://media.api-sports.io/football/teams/537.png',
  'espanyol': 'https://media.api-sports.io/football/teams/540.png',
  'alavés': 'https://media.api-sports.io/football/teams/542.png',
  'alaves': 'https://media.api-sports.io/football/teams/542.png',
  'leganés': 'https://media.api-sports.io/football/teams/745.png',
  'leganes': 'https://media.api-sports.io/football/teams/745.png',
  'valladolid': 'https://media.api-sports.io/football/teams/720.png',
  'atalanta': 'https://media.api-sports.io/football/teams/499.png',
  'as roma': 'https://media.api-sports.io/football/teams/497.png',
  'lazio': 'https://media.api-sports.io/football/teams/487.png',
  'napoli': 'https://media.api-sports.io/football/teams/492.png',
  'fiorentina': 'https://media.api-sports.io/football/teams/502.png',
  'bologna': 'https://media.api-sports.io/football/teams/500.png',
  'torino': 'https://media.api-sports.io/football/teams/503.png',
  'genoa': 'https://media.api-sports.io/football/teams/495.png',
  'monza': 'https://media.api-sports.io/football/teams/1579.png',
  'empoli': 'https://media.api-sports.io/football/teams/511.png',
  'lecce': 'https://media.api-sports.io/football/teams/867.png',
  'cagliari': 'https://media.api-sports.io/football/teams/490.png',
  'verona': 'https://media.api-sports.io/football/teams/504.png',
  'udinese': 'https://media.api-sports.io/football/teams/494.png',
  'parma': 'https://media.api-sports.io/football/teams/523.png',
  'como': 'https://media.api-sports.io/football/teams/1583.png',
  'venezia': 'https://media.api-sports.io/football/teams/518.png',
  'eintracht frankfurt': 'https://media.api-sports.io/football/teams/169.png',
  'vfb stuttgart': 'https://media.api-sports.io/football/teams/170.png',
  'friburgo': 'https://media.api-sports.io/football/teams/160.png',
  'werder bremen': 'https://media.api-sports.io/football/teams/162.png',
  'hoffenheim': 'https://media.api-sports.io/football/teams/167.png',
  'heidenheim': 'https://media.api-sports.io/football/teams/1822.png',
  "borussia m'gladbach": 'https://media.api-sports.io/football/teams/163.png',
  'wolfsburgo': 'https://media.api-sports.io/football/teams/161.png',
  'maguncia 05': 'https://media.api-sports.io/football/teams/164.png',
  'augsubrgo': 'https://media.api-sports.io/football/teams/172.png',
  'st. pauli': 'https://media.api-sports.io/football/teams/185.png',
  'holstein kiel': 'https://media.api-sports.io/football/teams/191.png',
  'unión berlín': 'https://media.api-sports.io/football/teams/182.png',
  'bochum': 'https://media.api-sports.io/football/teams/176.png',
  'marsella': 'https://media.api-sports.io/football/teams/81.png',
  'lyon': 'https://media.api-sports.io/football/teams/80.png',
  'lens': 'https://media.api-sports.io/football/teams/116.png',
  'niza': 'https://media.api-sports.io/football/teams/84.png',
  'reims': 'https://media.api-sports.io/football/teams/93.png',
  'rennes': 'https://media.api-sports.io/football/teams/94.png',
  'estrasburgo': 'https://media.api-sports.io/football/teams/76.png',
  'brest': 'https://media.api-sports.io/football/teams/106.png',
  'toulouse': 'https://media.api-sports.io/football/teams/96.png',
  'montpellier': 'https://media.api-sports.io/football/teams/82.png',
  'auxerre': 'https://media.api-sports.io/football/teams/77.png',
  'saint-étienne': 'https://media.api-sports.io/football/teams/89.png',
  'angers': 'https://media.api-sports.io/football/teams/79.png',
  'le havre': 'https://media.api-sports.io/football/teams/103.png',
  'nantes': 'https://media.api-sports.io/football/teams/83.png',
  'américa': 'https://media.api-sports.io/football/teams/2287.png',
  'america': 'https://media.api-sports.io/football/teams/2287.png',
  'cruz azul': 'https://media.api-sports.io/football/teams/2290.png',
  'tigres uanl': 'https://media.api-sports.io/football/teams/2289.png',
  'monterrey': 'https://media.api-sports.io/football/teams/2288.png',
  'guadalajara': 'https://media.api-sports.io/football/teams/2295.png',
  'chivas': 'https://media.api-sports.io/football/teams/2295.png',
  'pumas unam': 'https://media.api-sports.io/football/teams/2291.png',
  'toluca': 'https://media.api-sports.io/football/teams/2292.png',
  'pachuca': 'https://media.api-sports.io/football/teams/2293.png',
  'león': 'https://media.api-sports.io/football/teams/2296.png',
  'leon': 'https://media.api-sports.io/football/teams/2296.png',
  'santos laguna': 'https://media.api-sports.io/football/teams/2297.png',
  'atlas': 'https://media.api-sports.io/football/teams/2298.png',
  'tijuana': 'https://media.api-sports.io/football/teams/2301.png',
  'querétaro': 'https://media.api-sports.io/football/teams/2299.png',
  'queretaro': 'https://media.api-sports.io/football/teams/2299.png',
  'necaxa': 'https://media.api-sports.io/football/teams/2302.png',
  'mazatlán': 'https://media.api-sports.io/football/teams/10255.png',
  'mazatlan': 'https://media.api-sports.io/football/teams/10255.png',
  'puebla': 'https://media.api-sports.io/football/teams/2300.png',
  'atlético san luis': 'https://media.api-sports.io/football/teams/2303.png',
  'fc juárez': 'https://media.api-sports.io/football/teams/2304.png',
  'fc juarez': 'https://media.api-sports.io/football/teams/2304.png',
};

export function getTeamLogo(teamName: string): string {
  const nameLower = teamName.toLowerCase().trim();
  const countryCode = COUNTRY_CODES[nameLower];
  if (countryCode) {
    return `https://flagcdn.com/w80/${countryCode}.png`;
  }
  const clubLogo = CLUB_LOGOS[nameLower];
  if (clubLogo) {
    return clubLogo;
  }
  return `https://ui-avatars.com/api/?name=${encodeURIComponent(teamName)}&background=2A2A4A&color=ffffff&size=128`;
}

export function getLeagueLogo(leagueName: string): string {
  const nameLower = leagueName.toLowerCase();
  if (nameLower.includes('champions league')) {
    return 'https://media.api-sports.io/football/leagues/2.png';
  }
  if (nameLower.includes('world cup') || nameLower.includes('copa mundial') || nameLower.includes('mundial') || nameLower.includes('cup')) {
    return 'https://media.api-sports.io/football/leagues/1.png';
  }
  if (nameLower.includes('la liga') || nameLower.includes('laliga') || nameLower.includes('primera división') || nameLower.includes('primera division')) {
    return 'https://media.api-sports.io/football/leagues/140.png';
  }
  if (nameLower.includes('premier league') || nameLower.includes('inglaterra')) {
    return 'https://media.api-sports.io/football/leagues/39.png';
  }
  if (nameLower.includes('serie a') || nameLower.includes('italia')) {
    return 'https://media.api-sports.io/football/leagues/135.png';
  }
  if (nameLower.includes('bundesliga') || nameLower.includes('alemania')) {
    return 'https://media.api-sports.io/football/leagues/78.png';
  }
  if (nameLower.includes('ligue 1') || nameLower.includes('francia')) {
    return 'https://media.api-sports.io/football/leagues/61.png';
  }
  if (nameLower.includes('liga mx') || nameLower.includes('méxico') || nameLower.includes('mexico')) {
    return 'https://media.api-sports.io/football/leagues/262.png';
  }
  if (nameLower.includes('libertadores') || nameLower.includes('copa libertadores')) {
    return 'https://media.api-sports.io/football/leagues/13.png';
  }
  return `https://ui-avatars.com/api/?name=${encodeURIComponent(leagueName)}&background=1E1E38&color=ffffff&size=128`;
}
